{
 "title": "COVID-19",
 "tags": [
  "influxdb",
  "custom"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "State",
    "query": "SHOW TAG VALUES WITH KEY = \"state\""
   }
  ]
 },
 "panels": [
  {
   "title": "Deaths by day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deathIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths / Hospitalized / Positives",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state - Death",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT mean(\"death\") FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "death" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state - Hospitalized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "hospitalizedCumulative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state - Positives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "case" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths (-1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deathIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "death" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Currently Hospitalized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "hospitalizedCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "ICU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "inIcuCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Vent.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "onVentilatorCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Testing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state -  % positive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"positiveIncrease\") / last(\"totalTestResultsIncrease\")  FROM \"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_state -  Positive tests increases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT last(\"positiveIncrease\") FROM \"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(previous)",
     "select": [
      [
       { "params": [ "positiveIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state -  Tests increases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT last(\"totalTestResultsIncrease\") FROM \"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval) , \"state\" fill(previous)",
     "select": [
      [
       { "params": [ "totalTestResultsIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Positive cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "case" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative Hospitalizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "hospitalizedCumulative" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Additional Hospitalizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "hospitalizedIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Additional Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "positiveIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Pct of Positive tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state - Positives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT last(\"positiveIncrease\") / last(\"totalTestResultsIncrease\")   FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "hospitalizedIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Increase in hospitalizations / Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state - Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT mean(\"hospitalizedCurrently\") FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "hospitalizedCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state - Increase",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "hospitalizedIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state - ICU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT mean(\"hospitalizedCurrently\") FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "inIcuCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    },
    {
     "alias": "$tag_state - Vent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT mean(\"hospitalizedCurrently\") FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "onVentilatorCurrently" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths & Hospitalized Increases",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "covid19",
     "query": "SELECT last(\"deathIncrease\") as \"Deaths (Inc)\" ,last(\"hospitalizedIncrease\") as \"Hospitalized (Inc)\"   ,last(\"hospitalizedCurrently\") as \"Hospitalized\" ,last(\"inIcuCurrently\") as \"in ICU\"  ,last(\"onVentilatorCurrently\") as \"on Ventilator\"  FROM \"autogen\".\"covid19\" WHERE (\"state\" =~ /^$State$/) AND $timeFilter GROUP BY time($__interval) ORDER BY \"time\" DESC",
     "select": [
      [
       { "params": [ "deathIncrease" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$State$/" }
     ]
    }
   ]
  }
 ]
}